### ISSUE TITLE
Questions of deploying Bao in pilotscope

### ISSUE THREAD

**Issue by lucifer12346** [alibaba/pilotscope#2]
Since PostgreSQL 13.1 changes the function standart_planner() and _Bao: Making Learned Query Optimization Practical_ is deployed in PostgreSQL 12, there are errors when trying to set Bao on PostgreSQL 13.1.

When using command:
```
make USE_PGXS=1 install
```
Error:
```
In file included from main.c:10:
bao_planner.h:226:12: error: too few arguments to function ‘standard_planner’
  226 |     plan = standard_planner(query_copy, cursorOptions, boundParams);
      |            ^~~~~~~~~~~~~~~~
```
It looks like this issue is caused by the version of PostgreSQL.
And I wonder how to intergrate _Bao_ into pilotscope as _Lero_.

**Comment by duoyw** [comment]
We have verified the Bao algorithm in PIlotScope. However, we remove the related code due to its License. You can integrate Bao into PilotScope by inheriting the HintPushHandler, which will help you injecting the hint-set  into each input SQL query.

**Comment by duoyw** [comment]
We have verified the Bao algorithm in PIlotScope. However, we remove the Bao code due to its License. You can integrate Bao into PilotScope by inheriting the HintPushHandler, which will help you inject the hint set into each input SQL query. We provide two related codes for you. Then, you can use postgresql13.1 to develop Bao.
![image](https://github.com/alibaba/pilotscope/assets/31238100/61bf80ef-ff83-472c-a373-05b660e96257)
[bao_example.txt](https://github.com/alibaba/pilotscope/files/13782833/bao_example.txt)

**Comment by duoyw** [comment]
another code for collecting training data. 
[bao_pretraining_example_.txt](https://github.com/alibaba/pilotscope/files/13782919/bao_pretraining_example_.txt)

**Comment by lucifer12346** [comment]
Thank you very much!  But it looks like the codes in the picture are not given in the txt files.

> We have verified the Bao algorithm in PIlotScope. However, we remove the Bao code due to its License. You can integrate Bao into PilotScope by inheriting the HintPushHandler, which will help you inject the hint set into each input SQL query. We provide two related codes for you. Then, you can use postgresql13.1 to develop Bao. ![image](https://private-user-images.githubusercontent.com/31238100/293126423-61bf80ef-ff83-472c-a373-05b660e96257.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3ODAwOTcsIm5iZiI6MTcwMzc3OTc5NywicGF0aCI6Ii8zMTIzODEwMC8yOTMxMjY0MjMtNjFiZjgwZWYtZmY4My00NzJjLWEzNzMtMDViNjYwZTk2MjU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI4VDE2MDk1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1OGRmOGIzZDIxNDYwYmI2MmNkNGFiOGVkZDhkMmRhODliZGYwZjI0ZTkwZmZiNWYyM2VmYmJkOTkxMjMzYmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WeIEpFkZ0wHBZOSNrgEQv7QEdQfECdQDfxcqTtNiYss) [bao_example.txt](https://github.com/alibaba/pilotscope/files/13782833/bao_example.txt)

**Comment by duoyw** [comment]
A complete Bao example. 
[bao_example.txt](https://github.com/alibaba/pilotscope/files/13790387/bao_example.txt)

**Comment by lucifer12346** [comment]
It seems that there are some functions and classes are undefined but used in the previous code.
class ExperimentTimeEnum, BaoRegression, SparkPlanCompress, BaoPilotModel are undefined and function modify_sql_for_spark()  are undfined either.

**Comment by duoyw** [comment]
Yes, some functions have been removed from the lasted version, such as ExperimentTimeEnum. You can remove all functions/classes on Spark. BaoRegression is the model from Bao source code, and we can not provide it due to its License. You can download it from Bao source code.  You can build a BaoPilotModel referring to Lero.
