### ISSUE TITLE
Inquiry about implementation of NeuroCard

### ISSUE THREAD

**Issue by Leesangoh** [alibaba/pilotscope#7]
Thank you for your great work!

I am wondering if there are some implementation example of NeuroCard just like MSCN, which is provided in the repository.

It seems like NeuroCard has been implemented before (in the image), but I cannot find the example in the repository.

Would you mind if you could provide this?

Thanks!

<img width="612" alt="image" src="https://github.com/alibaba/pilotscope/assets/68114701/703399f8-3c4e-4119-9caf-8b402a28fd45">

**Comment by duoyw** [comment]
We apologize for any misunderstanding caused by our description. Upon analysis, we can confirm that all the algorithms mentioned in the document can indeed be executed through Pilotscope. However, due to resource constraints, we have only implemented one algorithm for each type of task. For cardinality estimation tasks, the MSCN algorithm has been employed. Should you encounter any issues while utilizing Pilotscope for neurocard, we will be proactive in responding to your inquiries.
